### ISSUE TITLE
Max slider setting currently broken

### ISSUE THREAD

**Issue by jwilmer** [rpsychologist/rpsychologist-com#45] opened 2022-09-15 12:45 UTC
Here's a video showing the broken thing (and a workaround): 
https://youtu.be/20N-O8r0GnM
I'm using Chrome Version 105.0.5195.102 (Official Build) (arm64) on MacOS Monterey 12.3.1

**Comment by rpsychologist** [comment] 2022-09-15 16:14
Thanks, but I think this is a duplicate of #8, see also #38

**Closed by rpsychologist** 2022-09-15 16:14 UTC
